/**
 * Icon.tsx — Drop-in replacement for `import { Feather } from '@expo/vector-icons'`
 *
 * Uses lucide-react-native (SVG-based) instead of font-based icons so no font
 * file loading is required. This permanently fixes icon rendering on Android
 * Expo Go, where expo-font TTF delivery through the Replit Metro proxy is
 * unreliable for physical devices.
 *
 * Usage (identical to @expo/vector-icons Feather):
 *   import { Feather } from '@/components/Icon';
 *   <Feather name="home" size={24} color="#000" />
 */

import React from 'react';
import type { ColorValue, StyleProp, ViewStyle } from 'react-native';
import {
  AlertCircle,
  AlertTriangle,
  Activity,
  Archive,
  ArrowLeft,
  ArrowRight,
  ArrowRightCircle,
  Award,
  BarChart2,
  Bell,
  BookOpen,
  Briefcase,
  Calendar,
  Camera,
  Check,
  CheckCircle,
  ChevronDown,
  ClipboardCheck,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Clock,
  Code,
  Coffee,
  Copy,
  Cpu,
  CreditCard,
  Database,
  DollarSign,
  Download,
  Droplet,
  Edit,
  Edit2,
  ExternalLink,
  Eye,
  EyeOff,
  FileText,
  Flag,
  Gift,
  Globe,
  Grid3x3 as Grid,
  Headphones,
  Heart,
  Home,
  Image as LucideImage,
  Inbox,
  Info,
  Key,
  Leaf,
  Layers,
  Link,
  List,
  Loader,
  Lock,
  LogIn,
  LogOut,
  Mail,
  Map,
  MapPin,
  Megaphone,
  MessageCircle,
  Mic,
  Minus,
  Monitor,
  MoreHorizontal,
  MoreVertical,
  Navigation,
  Package,
  Paperclip,
  Phone,
  Plus,
  PlusCircle,
  RefreshCw,
  Repeat,
  Ruler,
  Scissors,
  Search,
  Send,
  Settings,
  Shield,
  ShoppingBag,
  ShoppingCart,
  Slash,
  Sliders,
  Smile,
  Star,
  Store,
  Tag,
  ThumbsDown,
  ThumbsUp,
  Trash2,
  Truck,
  Tv,
  Upload,
  User,
  UserPlus,
  Users,
  UserX,
  Video,
  Wind,
  Wrench,
  X,
  XCircle,
  Zap,
} from 'lucide-react-native';
import type { LucideProps } from 'lucide-react-native';

// ─── icon map: Feather name → Lucide component ───────────────────────────────
const ICON_MAP = {
  'activity':           Activity,
  'alert-circle':       AlertCircle,
  'alert-triangle':     AlertTriangle,
  'archive':            Archive,
  'arrow-left':         ArrowLeft,
  'arrow-right':        ArrowRight,
  'arrow-right-circle': ArrowRightCircle,
  'award':              Award,
  'bar-chart-2':        BarChart2,
  'bell':               Bell,
  'briefcase':          Briefcase,
  'calendar':           Calendar,
  'camera':             Camera,
  'check':              Check,
  'check-circle':       CheckCircle,
  'chevron-down':       ChevronDown,
  'clipboard-check':    ClipboardCheck,
  'chevron-left':       ChevronLeft,
  'chevron-right':      ChevronRight,
  'chevron-up':         ChevronUp,
  'clock':              Clock,
  'code':               Code,
  'copy':               Copy,
  'cpu':                Cpu,
  'credit-card':        CreditCard,
  'database':           Database,
  'dollar-sign':        DollarSign,
  'download':           Download,
  'droplet':            Droplet,
  'edit':               Edit,
  'edit-2':             Edit2,
  'external-link':      ExternalLink,
  'eye':                Eye,
  'eye-off':            EyeOff,
  'file-text':          FileText,
  'flag':               Flag,
  'gift':               Gift,
  'globe':              Globe,
  'grid':               Grid,
  'headphones':         Headphones,
  'heart':              Heart,
  'home':               Home,
  'image':              LucideImage,
  'inbox':              Inbox,
  'info':               Info,
  'key':                Key,
  'leaf':               Leaf,
  'link':               Link,
  'list':               List,
  'loader':             Loader,
  'lock':               Lock,
  'log-in':             LogIn,
  'log-out':            LogOut,
  'mail':               Mail,
  'map-pin':            MapPin,
  'megaphone':          Megaphone,
  'message-circle':     MessageCircle,
  'mic':                Mic,
  'minus':              Minus,
  'monitor':            Monitor,
  'more-horizontal':    MoreHorizontal,
  'more-vertical':      MoreVertical,
  'navigation':         Navigation,
  'package':            Package,
  'paperclip':          Paperclip,
  'phone':              Phone,
  'plus':               Plus,
  'plus-circle':        PlusCircle,
  'refresh-cw':         RefreshCw,
  'repeat':             Repeat,
  'ruler':              Ruler,
  'search':             Search,
  'send':               Send,
  'settings':           Settings,
  'shield':             Shield,
  'shopping-bag':       ShoppingBag,
  'shopping-cart':      ShoppingCart,
  'slash':              Slash,
  'sliders':            Sliders,
  'smile':              Smile,
  'star':               Star,
  'tag':                Tag,
  'thumbs-down':        ThumbsDown,
  'thumbs-up':          ThumbsUp,
  'trash-2':            Trash2,
  'truck':              Truck,
  'tv':                 Tv,
  'upload':             Upload,
  'user':               User,
  'user-plus':          UserPlus,
  'users':              Users,
  'user-x':             UserX,
  'video':              Video,
  'wind':               Wind,
  'x':                  X,
  'x-circle':           XCircle,
  'zap':                Zap,
  // Proximity feature icons
  'book-open':  BookOpen,
  'book':       BookOpen,
  'coffee':     Coffee,
  'layers':     Layers,
  'map':        Map,
  'scissors':   Scissors,
  'store':      Store,
  'wrench':     Wrench,
  'tool':       Wrench,
} as const;

type FeatherName = keyof typeof ICON_MAP;

export interface FeatherProps {
  name: string;
  size?: number;
  color?: ColorValue | string;
  style?: StyleProp<ViewStyle>;
}

/**
 * Feather-compatible icon component backed by lucide-react-native (SVG).
 * Falls back to AlertCircle for unknown icon names so nothing crashes.
 */
export function Feather({ name, size = 24, color = 'black', style }: FeatherProps) {
  const Component: React.ComponentType<LucideProps> =
    ICON_MAP[name as FeatherName] ?? AlertCircle;
  return (
    <Component
      size={size}
      color={color as string}
      style={style as LucideProps['style']}
    />
  );
}

export default Feather;
