kind = "mobile"
previewPath = "/"
title = "BARDEC Mobile"
version = "1.0.0"
id = "artifacts/mobile"
router = "expo-domain"

[[services]]
name = "expo"
ensurePreviewReachable = "/status"
paths = [ "/" ]
localPort = 18115

[services.development]
run = "pnpm --filter @workspace/mobile run dev"

[services.production]
serve = "static"
publicDir = "dist"
build = [ "pnpm", "--filter", "@workspace/mobile", "run", "build:web" ]

[services.env]
PORT = "18115"
BASE_PATH = "/"
